#!/usr/bin/env zsh
export DOTFILES_DIR=$HOME/dotfiles

mumble() {
  printf "\\n$1\\n" "$@"
}

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install Homebrew
if ! command -v brew >/dev/null; then
  mumble "Installing Homebrew ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  mumble "Homebrew already exists"
fi

# Find or clone dotfiles
if [[ -a $DOTFILES_DIR ]]; then
  mumble "Dotfiles exist, updating"
  ( cd $DOTFILES_DIR && git pull origin main )
else
  mumble "Dotfiles don't exist, cloning to $DOTFILES_DIR"
  git clone https://github.com/agerdes/dotfiles.git $DOTFILES_DIR
fi

# Install Homebrew bundle
if brew bundle check --file=$DOTFILES_DIR/brew/Brewfile >/dev/null; then
  mumble "Homebrew bundle is up to date."
else
  mumble "Homebrew bundle is out of date, updating.."
  brew update
  brew doctor
  brew bundle --file=$DOTFILES_DIR/brew/Brewfile
fi

# Source zshrc
source $DOTFILES_DIR/zsh/zshrc

# Run each ./*/setup
setup_files=($DOTFILES_DIR/*/setup)
for file in $setup_files; do
  mumble "Running setup script at $file"
  $file
done
