export PATH=/opt/homebrew/bin:/usr/local/bin:$PATH
export EDITOR='vim'
export GPG_TTY=$(tty)
# LS colors, made with https://geoff.greer.fm/lscolors/
export LSCOLORS="Exfxcxdxbxegedabagacad"
# Pick-up command history where OMZ left off
HISTFILE=~/.zsh_history
HISTSIZE=32768
SAVEHIST=10000
setopt HIST_IGNORE_SPACE
setopt HIST_EXPIRE_DUPS_FIRST
HISTORY_IGNORE="(ls|ls *|cd *|pass|pwd|exit|date|* --help|git status)"
# History ignores fails  - http://www.zsh.org/mla/users//2014/msg00715.html
zshaddhistory() { whence ${${(z)1}[1]} >| /dev/null || return 1 }

fpath=( $HOME/dotfiles/zsh/bin "${fpath[@]}" )

autoload -Uz apps
autoload -Uz backup
autoload -Uz launcher

# Use ripgrep for fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden --no-ignore-vcs --smart-case --glob "!.git/*"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1
# vim mode
bindkey -v
bindkey -v '^?' backward-delete-char
# Open command line in vim
autoload edit-command-line
zle -N edit-command-line
bindkey -r "^l"
bindkey '^l' vi-cmd-mode
bindkey -M vicmd "^l" edit-command-line

# key bindings
zle -N launcher
bindkey '^F' launcher
zle -N apps
bindkey '^A' apps

# aliases
ls -G . &>/dev/null && alias ls='ls -G'
alias ap="cat >> $1"
alias bc="bc -lq"
alias goo="ddgr -n 3 $1"
alias gratitude="vim ~/Notes/Gratitude/$(date '+%Y-%m-%d').txt"
alias in="cat >> ~/Notes/Inbox.txt"
alias journal="vim ~/Notes/Journal/$(date '+%Y-%m-%d').txt"
alias pas="pass -c $1 && pass $1 | rg 'login:' | xargs -I{} terminal-notifier -message {} -title 'Password Copied'"
alias zshconfig="vim ~/.zshrc"
alias zzz="pmset sleepnow"

# Use pure theme
autoload -U promptinit; promptinit
prompt pure

# git completion
autoload -Uz compinit && compinit

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# chruby
source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh

# fish-like auto suggestions
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# fish-like command syntax highlighting - needs to be the last source in the file
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

