export PATH=/usr/local/bin:$PATH
export LANG=en_US.UTF-8
export ARCHFLAGS="-arch x86_64"
export EDITOR='vim'
export GPG_TTY=$(tty)
# LS colors, made with https://geoff.greer.fm/lscolors/
export LSCOLORS="Exfxcxdxbxegedabagacad"
# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
# Pick-up command history where OMZ left off
HISTFILE="$HOME/.zsh_history"
HISTSIZE=32768
SAVEHIST=10000
export HISTCONTROL=ignoredups
# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# chruby
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# Use ripgrep for fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden --no-ignore-vcs --smart-case --glob "!.git/*"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

function launchzilla() {
  local cmd="command rg --files --smart-case \
    ~/Notes \
    ~/Code \
    ~/Desktop \
    ~/Documents \
    ~/Downloads"
  local out=$(eval $cmd | fzf)

  if [ -f "$out" ]; then
    $EDITOR "$out" < /dev/tty
  elif [ -d "$out" ]; then
    cd "$out"
    zle reset-prompt
  fi
}


function apps() {
  local search="command find /Applications /System/Applications \
    /System/Applications/Utilities -iname '*.app' -maxdepth 1"
  local out=$(eval $search | fzf)

  if [ -f "$out" ]; then
    $EDITOR "$out" < /dev/tty
  elif [ -d "$out" ]; then
    open -a "$out"
    zle reset-prompt
  fi
}


# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1
# vim mode
bindkey -v
bindkey -v '^?' backward-delete-char
# Open command line in vim
autoload edit-command-line
zle -N edit-command-line
bindkey -r "^l"
bindkey '^l' vi-cmd-mode
bindkey -M vicmd "^l" edit-command-line

# key bindings
zle -N launchzilla
bindkey '^F' launchzilla
zle -N apps
bindkey '^A' apps


# aliases
ls -G . &>/dev/null && alias ls='ls -G'
alias ap="cat >> $1"
alias bc="bc -lq"
alias fort="ssh aaron@45.55.251.140 -p30001"
alias goo="ddgr -n 3 $1"
alias gratitude="vim ~/Notes/Gratitude/$(date '+%Y-%m-%d').txt"
alias in="cat >> ~/Notes/Inbox.txt"
alias journal="vim ~/Notes/Journal/$(date '+%Y-%m-%d').txt"
alias pas="pass -c $1 && pass $1 | rg 'login:' | xargs -I{} terminal-notifier -message {} -title 'Password Copied'"
alias zshconfig="vim ~/.zshrc"
alias zzz="pmset sleepnow"


# Use pure theme
fpath=("$HOME/dotfiles/zsh/functions" $fpath)
autoload -U promptinit; promptinit
prompt pure

# git completion
autoload -Uz compinit && compinit

# fish-like auto suggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# fish-like command syntax highlighting - needs to be the last source in the file
source /Users/agerdes/dotfiles/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
