#!/bin/zsh

defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$DOTFILES_DIR/iterm2"
# Tell iTerm2 to use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Install Gruvbox iTerm colors
open "$DOTFILES_DIR/iterm2/gruvbox.itermcolors"
